server:
  port: 8761

spring:
  application:
    name: eureka-discovery-server
eureka:
  instance:
    hostname: localhost # http://192.168.0.14/
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8671
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000
